name: flutter_paystack_example
description: Demonstrates how to use the flutter_paystack plugin.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_paystack:
    path: ../

flutter:
  uses-material-design: true


environment:
  sdk: ">=3.0.0 <3.7.0"
  flutter: ">=2.12.1 <3.5.0"  
