name: flutter_paystack
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 1.0.4+1
author: Wilberforce Uwadiegwu <faradaywilly@gmail.com>
homepage: https://github.com/wilburt/flutter_paystack

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.18.0
  meta: ^1.15.0
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.15
  mockito: ^5.4.4


flutter:
  plugin:
    platforms:
      android:
        package: co.paystack.flutterpaystack
        pluginClass:  FlutterPaystackPlugin
      ios:
        pluginClass:  FlutterPaystackPlugin

  assets:
   - assets/images/



environment:
  sdk: ">=3.0.0 <3.7.0"
  flutter: ">=2.12.1 <3.5.0"