name: flutter_paystack
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 1.0.5
author: Wilberforce Uwadiegwu <faradaywilly@gmail.com>
homepage: https://github.com/wilburt/flutter_paystack

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  intl: ^0.18.1
  meta: ^1.9.1
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.16
  mockito: ^5.4.2


flutter:
  plugin:
    platforms:
      android:
        package: co.paystack.flutterpaystack
        pluginClass: FlutterPaystackPlugin
      ios:
        pluginClass: FlutterPaystackPlugin

  assets:
  - assets/images/



environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.0.0"
